# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 17:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('attending_count', models.IntegerField()),
                ('facebook_id', models.TextField(blank=True, null=True, unique=True)),
                ('owner', models.TextField()),
                ('cover', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.TextField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Place'),
        ),
    ]
