# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_end_tiem'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
