# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_place_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
