# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_place_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_tiem',
            new_name='end_time',
        ),
    ]
